spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      post:
        enabled: true
  info:
    env:
      enabled: true

logging:
  level:
    com.flightmonitor: DEBUG
    org.springframework: INFO
